version: '3.8'

services:

  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"
    
  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    command: npm run start:dev
    working_dir: /usr/src/app
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
    develop:
      watch:
        - action: sync
          path: ./api-gateway
          target: /usr/src/app

  authentication-ms:
    build: 
      context: ./authentication-ms
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    command: npm run start:dev
    depends_on:
      authentication-db:
        condition: service_healthy
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://postgres:123456@authentication-db:5432/authentication_db?schema=public
    develop:
      watch:
        - action: sync
          path: ./authentication-ms
          target: /usr/src/app
          
  authentication-db:
    container_name: authentication-db
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=authentication_db
    ports:
      - "5432:5432"
    volumes:
      - ./authentication-ms/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d authentication_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
